name = "espidf_driver_i2c"
description = "Ada/ESP-IDF I2C master/slave driver"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded", "espidf", "driver", "i2c"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
espidf = "*"
